name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    if: contains(github.event.label.name, 'Bug') || contains(github.event.labels.*.name, 'Bug')
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "DanGrantMiller"
          ado_project: "GitTest"
          ado_area_path: "GitTest"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_close_state: "Closed"
          ado_bypassrules: true
